# Server
server.port=8089

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://3.136.16.248:5432/banking-proccesses?createDatabaseIfNotExist=true
spring.datasource.username=postgres
spring.datasource.password=postgres13
spring.datasource.driverClassName=org.postgresql.Driver

# JPA Configuration
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.com.banco.rpa=DEBUG
#logging.file.name=logs/banking-rpa.log

# Session Configuration
server.servlet.session.timeout=60m
spring.session.store-type=none

# Banking URLs
rpa.api.base-url=http://localhost:8088

# Clave de encriptacion para API Keys (debe ser de al menos 16 caracteres)
encryption.secret-key=superSecretKey12