# Server
server.port=8089

# PostgreSQL Configuration Server AWS
#spring.datasource.url=jdbc:postgresql://3.136.16.248:5432/banking-proccesses?createDatabaseIfNotExist=true
#spring.datasource.username=postgres
#spring.datasource.password=postgres13

# PostgreSQL Configuration Windows server
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/banking-proccesses
spring.datasource.username=bancking_app
spring.datasource.password=3288Caridad$$

spring.datasource.driverClassName=org.postgresql.Driver

# JPA Configuration
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging INFO en produccion DEBUG solo para diagnosticar errores
logging.level.com.banco.rpa=DEBUG
#logging.level.com.banco.rpa=INFO
#logging.file.name=logs/banking-rpa.log

# Session Configuration
server.servlet.session.timeout=60m
spring.session.store-type=none

# Banking URLs
rpa.api.base-url=http://127.0.0.1:8088

# Clave de encriptacion para API Keys (debe ser de al menos 16 caracteres)
encryption.secret-key=superSecretKey12